### ISSUE TITLE
Free'ing of static memory

### ISSUE THREAD

**Issue by SakalisC** [ChrisLidbury/CLSmith#5]
Depending on the input given to `cl_launcher`, it might lead to free'ing the pointers to `global_dims` and `local_dims` while pointing to the empty string "" allocated in the static data section of the application, which in turn causes the application to terminate.

The offending code is in lines [325](https://github.com/ChrisLidbury/CLSmith/blob/master/src/CLSmith/cl_launcher.c#L325) and [326](https://github.com/ChrisLidbury/CLSmith/blob/master/src/CLSmith/cl_launcher.c#L326) in the [`cl_launcher`](https://github.com/ChrisLidbury/CLSmith/blob/master/src/CLSmith/cl_launcher.c) file.

**Comment by mpflanzer** [comment]
I have been working on a version of cl_launcher using the new C++ bindings for OpenCL. Currently it is not really tested but you might want to have a look: https://github.com/mpflanzer/CLSmith/tree/cl_launcher
I should also note that it the C++ version needs C++14 and is at the moment not completely compatible to the C version.

**Comment by afd** [comment]
Andrei, could you have a look into this one, please?

Cheers

Ally

**Comment by afd** [comment]
Sounds good, Moritz.  Do you envisage that this would replace the C 
version?  I guess the only blocker could be if some of the devices we 
want to test have trouble compiling the flavour of C++ you are using.

A

**Comment by mpflanzer** [comment]
Yes, eventually the C++ version could replace the current C version. I think the code is cleaner and easier to extend in the future. But I am not yet sure if my current version is the best way of using the new OpenCL API. Much nicer would have been to use the even newer cl2.hpp (it can also be used for CL 1.x) but I could not get it running on Mac, so I guess support is still limited.

I might have some questions about some ifdefs in the source code but I will write an email when I have a bit more time.

I just used C++14 for now since it made some things a bit nicer. But stepping down to C++11 should be a problem if C++14 is not supported everywhere.

**Comment by 0152la** [comment]
Hi, @SakalisC.

Thanks for bringing the issue to our attention. I have pushed a fix to it now. Please tell us if you encounter any other issues with the code.

**Comment by SakalisC** [comment]
Thank you for fixing the issue. At some point I will also get around to trying the C++ launcher that @mpflanzer is working on, but I am a bit preoccupied with something different at the moment.
